name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
defaults:
  run:
    working-directory: ./indexer

jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - name: Change directory to indexer
        run: cd indexer
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: yarn
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Install subql-node-ethereum
        run: yarn global add @subql/node-ethereum
      - name: Run tests with Subquery Node
        run: subql-node-ethereum test -f ${{ github.workspace }}
